ikasan.dashboard.extract.enabled=true
ikasan.dashboard.extract.username=admin
ikasan.dashboard.extract.password=admin
module.name=${artifactId}
ikasan.dashboard.extract.base.url=http://localhost:9090
ikasan.dashboard.extract.exceptions=true

zip.output.dir=./

spring.main.web-application-type=none
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.XADataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.ikasan.dashboard.DashboardClientAutoConfiguration,org.springframework.boot.autoconfigure.context.MessageSourceAutoConfiguration,org.ikasan.job.orchestration.JobOrchestrationAutoConfiguration,org.ikasan.orchestration.service.context.ContextServiceAutoConfiguration,org.ikasan.job.orchestration.rest.client.JobOrchestrationRestDashboardClientAutoConfiguration,org.ikasan.rest.client.ModuleRestClientAutoConfiguration