<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>\${groupId}</groupId>
        <artifactId>\${artifactId}-parent</artifactId>
        <version>\${version}</version>
    </parent>

    <groupId>\${groupId}</groupId>
    <artifactId>\${artifactId}</artifactId>
    <packaging>jar</packaging>
    <version>\${version}</version>
    <name>\${artifactId} Job Plan Builder Demo</name>
    <description>The purpose of this module is to demonstate the job plan builder features of the Ikasan Enterprise Scheduler</description>


    <dependencies>
        <dependency>
            <groupId>org.ikasan</groupId>
            <artifactId>ikasan-job-orchestration-builder</artifactId>
            <version>\${version.ikasan}</version>
        </dependency>

        <dependency>
            <groupId>org.ikasan</groupId>
            <artifactId>ikasan-job-orchestration-model</artifactId>
            <version>\${version.ikasan}</version>
        </dependency>

        <dependency>
            <groupId>org.ikasan</groupId>
            <artifactId>ikasan-job-orchestration-rest-dashboard-client</artifactId>
            <version>\${version.ikasan}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.ikasan</groupId>
                    <artifactId>ikasan-configuration-service</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.ikasan</groupId>
            <artifactId>ikasan-job-orchestration-service</artifactId>
            <version>\${version.ikasan}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.ikasan</groupId>
                    <artifactId>ikasan-eip-standalone</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.ikasan</groupId>
                    <artifactId>ikasan-h2-standalone-persistence</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.ikasan</groupId>
                    <artifactId>ikasan-configuration-service</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <version>1.4.14</version>
        </dependency>

        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.13</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>\${version.org.springboot}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>